language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"
  - "pypy"  # PyPy2 2.5.0
# command to install dependencies
install:
  - pip install nose
  - pip install coverage 
# command to run tests
script: nosetests -v test/test_calculator.py --with-coverage
